import { experimental_evaluate as evaluate } from "ai";
import { CATEGORIES, type Category } from "@/db/schema";

export const JEV_MODEL = "typesafe-ai/jev";

export type ClassifyInput = {
  fromName: string;
  fromEmail: string;
  subject: string;
  snippet: string;
  receivedAt: number;
  hasUnsubscribe: boolean;
  isReplyToMe: boolean;
};

export type Classification = {
  category: Category;
  categoryProbs: Record<string, number>;
  urgency: number; // 1..5
  isPersonal: number; // P(true)
  lowConfidence: boolean;
  model: string;
};

/** Remove tracking URLs, markdown image syntax, and angle-bracketed links that add noise without signal. */
export function stripNoise(text: string): string {
  return text
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/<https?:\/\/[^>]+>/g, " ")
    .replace(/https?:\/\/\S+/g, " ")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function buildState(m: ClassifyInput): string {
  return [
    `From: ${m.fromName} <${m.fromEmail}>`,
    `Subject: ${m.subject || "(no subject)"}`,
    `Received: ${new Date(m.receivedAt).toISOString()}`,
    `Has unsubscribe header: ${m.hasUnsubscribe ? "yes" : "no"}`,
    `User has previously replied in this thread: ${m.isReplyToMe ? "yes" : "no"}`,
    "",
    "Body:",
    stripNoise(m.snippet) || "(empty)",
  ].join("\n");
}

const QUESTIONS = {
  category: {
    type: "choice",
    instructions:
      "Which lane does this email belong in? Judge from the sender, subject, headers, and body together.",
    criteria: {
      needs_reply:
        "A real person expects a reply from the recipient: a colleague, customer, friend, or existing contact asking something or continuing a conversation.",
      updates:
        "Transactional or informational mail about the recipient's own accounts and activity: bank and card transaction alerts, OTPs and security notices, order, delivery, and booking status, receipts and invoices, bill reminders, service alarms, calendar or system notifications. Automated, addressed to the recipient, not trying to sell anything.",
      promotional:
        "Marketing: newsletters, campaigns, discounts, product announcements, event invitations, and content digests sent to a list. Usually has an unsubscribe link and is not about a specific transaction of the recipient.",
      sales:
        "Unsolicited cold outreach from a vendor, agency, or recruiter trying to start a conversation or book a call with the recipient.",
      spam: "Scams, phishing, fake invoices, or junk with no legitimate purpose.",
    },
  },
  urgency: {
    type: "score",
    instructions:
      "How urgently does this email need a reply from the recipient? Pick the level that best matches.",
    criteria: [
      "No reply needed, or no time pressure at all",
      "A reply within a week is fine",
      "A reply within a few days is expected",
      "A reply today is expected",
      "A person is blocked, or a deadline falls within 24 hours",
    ],
  },
  isPersonal: {
    type: "boolean",
    instructions:
      "Was this email written by a human specifically to this recipient, rather than sent to a list or generated by a system?",
  },
} as const;

export class GatewayForbiddenError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GatewayForbiddenError";
  }
}

/** Thrown when the gateway keeps returning 429 after the retry. The caller should stop for this run. */
export class GatewayRateLimitedError extends Error {
  retryAfterMs: number | null;
  constructor(message: string, retryAfterMs: number | null) {
    super(message);
    this.name = "GatewayRateLimitedError";
    this.retryAfterMs = retryAfterMs;
  }
}

type GatewayErr = { statusCode?: number; message?: string; responseHeaders?: Record<string, string> };

function statusOf(err: unknown): number | undefined {
  return (err as GatewayErr)?.statusCode;
}

function retryAfterMs(err: unknown): number | null {
  const h = (err as GatewayErr)?.responseHeaders?.["retry-after"];
  if (!h) return null;
  const s = Number(h);
  if (Number.isFinite(s) && s >= 0) return s * 1000;
  const d = Date.parse(h);
  return Number.isNaN(d) ? null : Math.max(0, d - Date.now());
}

export async function classifyMessage(m: ClassifyInput): Promise<Classification> {
  const state = buildState(m);
  const run = () => evaluate({ model: JEV_MODEL, state, questions: QUESTIONS, maxRetries: 0 });

  let result: Awaited<ReturnType<typeof run>>;
  try {
    result = await run();
  } catch (err) {
    const status = statusOf(err);
    if (status === 429) {
      const wait = retryAfterMs(err) ?? 5000;
      await new Promise((r) => setTimeout(r, Math.min(wait, 30_000)));
      try {
        result = await run();
      } catch (err2) {
        if (statusOf(err2) === 429) {
          throw new GatewayRateLimitedError((err2 as GatewayErr).message ?? "rate limited", retryAfterMs(err2));
        }
        throw err2;
      }
    } else if (status === 403) {
      throw new GatewayForbiddenError((err as GatewayErr).message ?? "forbidden");
    } else {
      throw err;
    }
  }

  const cat = result.answers.category;
  const urg = result.answers.urgency;
  const per = result.answers.isPersonal;

  const probs = cat.probabilities ?? { [cat.choice]: 1 };
  const sorted = Object.values(probs).sort((a, b) => b - a);
  const lowConfidence = sorted.length > 1 && sorted[0] - sorted[1] < 0.15;

  const category = (CATEGORIES as readonly string[]).includes(cat.choice)
    ? (cat.choice as Category)
    : "promotional";

  return {
    category,
    categoryProbs: probs,
    urgency: Math.min(5, Math.max(1, Math.round(urg.score) + 1)),
    isPersonal: per.probability,
    lowConfidence,
    model: result.response?.modelId ?? JEV_MODEL,
  };
}
